### ISSUE TITLE
Unable to hide one reputation only

### ISSUE THREAD

**Issue by Olivier024** [teelolws/InactiveReputationHeaders#10]
As seen in the screenshot above.

I let all my DF rep activ and hide all the others.
Work for all, but when i finish hiding MoP rep, this one appear and is not hiding even if done correctly.

![Capture d'écran 2024-02-18 074347](https://github.com/teelolws/InactiveReputationHeaders/assets/150658863/2e861dc4-f81a-4f9c-9046-08afe15419d8)

**Comment by teelolws** [comment]
You'll probably find its happening even without the addon. This is with the addon disabled, thats happening to Horde and Cataclysm and a few others to me:
![image](https://github.com/teelolws/InactiveReputationHeaders/assets/49792789/84a6c174-d4c3-4aca-9119-8ae4492392ba)

This might fix it. I wasn't able to get my Mists of Pandaria to display like yours though.
