### ISSUE TITLE
Conflict with addon "M+ Adventure Guide"

### ISSUE THREAD

**Issue by n-jones0** [teelolws/InactiveReputationHeaders#12]
When both this addon and [M+ Adventure Guide](https://www.curseforge.com/wow/addons/mplus-adventure-guide) are enabled, attempting to transfer currency fails with the message:

![image](https://github.com/user-attachments/assets/d54928aa-b10a-4245-939f-e101da6e5611)

Using either addon by themself causes no issue. Tested with these two addons being the only two loaded.

Inactive Reputation Headers veresion: r34 (2024-07-27)
M+ Adventure Guide version: 11.0-005 (2024-07-27)

**Comment by teelolws** [comment]
Strange. This addon doesn't do anything to the currency UI.
