### ISSUE TITLE
[BUG] Issues with The War Within Reputations

### ISSUE THREAD

**Issue by Calesta** [teelolws/InactiveReputationHeaders#14]
Using the latest version (r34), I see issues with The War Within reputations -- both headers and individual factions.

Without the addon loaded, I see this.

![RepPane1](https://github.com/user-attachments/assets/896b814f-441d-4bf2-a382-54125b0fd5d4)

With the addon loaded, I see this.

![RepPane2](https://github.com/user-attachments/assets/f529089f-baf3-4b74-a08b-43107673578a)

The screenshots were taken at different times so please ignore the fact that the reputation levels don't match as that isn't related to this issue.  You'll note that the Council of Dornogal shows up as a header twice and never as an individual faction.  I'm not quite sure what's going on here and I don't see any reported issue of it so I thought I'd make one in case it's something you'd be able to fix.

Thanks for such a useful addon!

**Comment by teelolws** [comment]
Some other addon is doing this. It doesn't happen when I've turned them all off. Will have to go through my addons to work out which one is doing it.

**Comment by teelolws** [comment]
Actually... I got the issue when I first saw your ticket and checked. But its not happening anymore. Maybe it was a Blizzard problem and they fixed it?

**Comment by n-jones0** [comment]
Can confirm that it's still happening with just this addon loaded:

![image](https://github.com/user-attachments/assets/99f4dd68-e5cb-4b1d-90b9-6960eec1715b)

**Comment by n-jones0** [comment]
You might be right about it being a Blizz issue, it's showing like that with it off, too....

**Comment by teelolws** [comment]
I've tried different characters and various situations. I can't seem to get the issue to come back.

**Comment by Calesta** [comment]
I logged into the game tonight and it looked 'normal'.  I took a portal to Dornogal, turned in the world quest that awarded reputation and I got summoned to the raid. I happen to check again and it had the double headers.  So maybe it's related to when the game 'reloads' into a zone or when reputation is earned?
