### ISSUE TITLE
Issue reported by TheKrowi on CF: Conflict with Titan Panel Reputations

### ISSUE THREAD

**Issue by teelolws** [teelolws/InactiveReputationHeaders#2]
![image](https://user-images.githubusercontent.com/49792789/198221970-17d60eac-28a8-4da0-ac2f-bbd3044844c8.png)

**Comment by teelolws** [comment]
Could not reproduce this issue while running TitanReputations and IRH. Tried on a number of characters with different reputation setups. Need more information about the players circumstances. Did it happen at login? How many reputations normally shown/hidden. IRH up to date?

**Comment by TheKrowi** [comment]
It looks like it's fixed with an update of either of the addons.
