### ISSUE TITLE
Addon is causing my game to freeze up for short periods of time.

### ISSUE THREAD

**Issue by antiharmonic** [teelolws/InactiveReputationHeaders#3]
I've disabled every addon one by one to narrow it down to this addon.

Whenever I get reputation (quest completion, world quest completion, killing mobs that award rep, etc), or open my character pane/rep pane, the game freezes/stutters for anyway from half a second to a couple of seconds.

This started happening after 10.0.

**Comment by teelolws** [comment]
Looks like it happens if you have lots and lots of reputations. I hadn't noticed as I have almost all of them marked inactive already. I'll see if theres any improvements I can make.

**Comment by teelolws** [comment]
I think I've got it. This commit will limit some of the processing it does. I'm going to give it a day or so to see if I spot any problems with it.

Heres a beta, let me know if you get any problems:

[InactiveReputationHeaders.zip](https://github.com/teelolws/InactiveReputationHeaders/files/10079587/InactiveReputationHeaders.zip)

**Comment by antiharmonic** [comment]
I've been able to complete world quests and daily quests awarding rep without any freezing.

Thanks so much!
