### ISSUE TITLE
Rep list exploding with latest patch

### ISSUE THREAD

**Issue by SirJorb** [teelolws/InactiveReputationHeaders#9]
Looks like some of the code for the rep pane may have changed with 10.2, as the rep list is exploding now. Some reps are listed with no names, and scrolling down sometimes causes the entire rep frame to become uninteractive (can no longer scroll, click, etc) until reload.

2x FrameXML/ReputationFrame.lua:194: attempt to concatenate local 'standingID' (a nil value)
[string "@FrameXML/ReputationFrame.lua"]:194: in function <FrameXML/ReputationFrame.lua:129>
[string "=[C]"]: in function 'ReputationFrame_InitReputationRow'
[string "@FrameXML/ReputationFrame.lua"]:17: in function `initializer'
[string "@SharedXML/Scroll/ScrollBoxListView.lua"]:382: in function 'InvokeInitializer'
[string "@SharedXML/Scroll/ScrollBoxListView.lua"]:391: in function 'InvokeInitializers'
[string "@SharedXML/Scroll/ScrollBox.lua"]:718: in function 'Update'
[string "@SharedXML/Scroll/ScrollBox.lua"]:258: in function 'SetScrollPercentageInternal'
[string "@SharedXML/Scroll/ScrollBox.lua"]:250: in function 'SetScrollPercentage'
[string "@SharedXML/Scroll/ScrollController.lua"]:98: in function 'ScrollInDirection'
[string "@SharedXML/Scroll/ScrollBox.lua"]:232: in function 'ScrollInDirection'
[string "@SharedXML/Scroll/ScrollController.lua"]:89: in function <SharedXML/Scroll/ScrollController.lua:87>

Locals:
factionRow = Button {
 0 = <userdata>
 GetData = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:96
 index = 29
 ElementDataMatches = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:105
 GetOrderIndex = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:110
 SetOrderIndex = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:114
 OnClick = <function> defined @FrameXML/ReputationFrame.lua:409
 Container = Frame {
 }
 OnLoad = <function> defined @FrameXML/ReputationFrame.lua:399
 standingText = "Hated"
 ShowFriendshipReputationTooltip = <function> defined @FrameXML/ReputationFrame.lua:454
 OnLeave = <function> defined @FrameXML/ReputationFrame.lua:443
 ShowMajorFactionRenownTooltip = <function> defined @FrameXML/ReputationFrame.lua:476
 hasRep = true
 ParagonReputationHook = true
 OnEnter = <function> defined @FrameXML/ReputationFrame.lua:424
 rolloverText = "|cffffffff 31,175 / 36,000|r"
 GetElementData = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:96
}
elementData = <table> {
 index = 29
}
factionIndex = 29
factionContainer = Frame {
 0 = <userdata>
 ExpandOrCollapseButton = Button {
 }
 Name = FontString {
 }
 Background = Texture {
 }
 Paragon = Frame {
 }
 ReputationBar = StatusBar {
 }
}
factionBar = StatusBar {
 0 = <userdata>
 Highlight2 = Texture {
 }
 FactionStanding = FontString {
 }
 LeftTexture = Texture {
 }
 RightTexture = Texture {
 }
 AtWarHighlight1 = Texture {
 }
 AtWarHighlight2 = Texture {
 }
 BonusIcon = Frame {
 }
 Highlight1 = Texture {
 }
}
factionTitle = FontString {
 0 = <userdata>
}
factionButton = Button {
 0 = <userdata>
 Highlight = Texture {
 }
}
factionStanding = FontString {
 0 = <userdata>
}
name = nil
description = nil
standingID = nil
barMin = nil
barMax = nil
barValue = nil
atWarWith = nil
canToggleAtWar = nil
isHeader = nil
isCollapsed = nil
hasRep = nil
isWatched = nil
isChild = nil
factionID = nil
hasBonusRepGain = nil
canSetInactive = nil
colorIndex = nil
barColor = nil
factionStandingtext = nil
isParagon = nil
isCapped = nil
isMajorFaction = nil
repInfo = nil
gender = 3
(*temporary) = <function> defined =[C]:-1
(*temporary) = "FACTION_STANDING_LABEL"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'standingID' (a nil value)"

**Comment by teelolws** [comment]
I'm having the same issue. You'll get this error even with the addon disabled. Something has gone wrong with the base UI and I'm waiting to see if Blizzard fixes it.

**Comment by teelolws** [comment]
It seems the default UI no longer likes us marking the "Guild" faction as inactive. I wrote this to mark it active again:

/run for i = 1, 400 do if select(14, GetFactionInfo(i)) == 1168 then SetFactionActive(i) end end
